### ISSUE TITLE
Скорость игры

### ISSUE THREAD

**Issue by Burize** [mrNemoZero/life#1]
При каждом нажатии на "Старт" скорость игры увеличивается: Старт->Пауза->Старт будет двойная скорость.

**Comment by mrNemoZero** [comment]
ппц) Даже не задумался о том, как работает функция на самом деле,когда использовал setInterval()

**Comment by mrNemoZero** [comment]
А ты сам же закрываешь ишью, как проверишь?

**Comment by Burize** [comment]
Уже близко)))
Нужно сделать проверку на то, что игра уже запущена и не добавлять еще 1 setInterval. При паузе сейчас убирается последний setInterval. Поэтому если раз 10 нажать на "старт", то игру уже не остановишь.
