### ISSUE TITLE
Тесты

### ISSUE THREAD

**Issue by Burize** [mrNemoZero/life#11]
У тебя все тесты выполняются?

![2017-10-12 16 29 58](https://user-images.githubusercontent.com/22253666/31489417-bf3fafda-af6a-11e7-9db7-025939dbb511.png)

**Comment by mrNemoZero** [comment]
хмм, я помню не выполнялись некоторые тесты если браузер не в фокусе был, но вот у модели точно проходили все.Ну завтра перепроверю их
