### ISSUE TITLE
В package не использовать глобальных переменных

### ISSUE THREAD

**Issue by Burize** [mrNemoZero/life#12]
```
"dev": "webpack-dev-server --config webpack/webpack.config.js",
    "build": "webpack --config webpack/webpack.config.js",
    "test": "./node_modules/.bin/karma start karma/karma.conf.js"
```
У тебя для кармы правильно задан локальный путь, а webpack и devserver задан глобально. Так лучше не делать: у меня может быть установлен, допустим 2 webpack глобально, а в проекте используется (допустим) 3 webpack, и тогда могут быть конфликты при запуске.

**Comment by mrNemoZero** [comment]
Понял, у меня в втором макете тоже глобально заданы, там тоже переделаю
