### ISSUE TITLE
Тайпскрипт ошибки в тестах

### ISSUE THREAD

**Issue by shevdi** [mrNemoZero/life#13]
Тесты собираются, но тайпскрипт выдает ошибки.

**Comment by mrNemoZero** [comment]
А вот,что делать с ошибками на приватность функции? Сделать их публичными из-за тестов мне кажется это не правильною Или их проверять через то на что они влияют? 
Например:
у меня есть приватная функция  _isInputCorrect(number), которая проверяет,что бы входящее значениее ширины или высоты было неотрицательным числом, если число норм то перерисовывать. Т.е. проверить ее,что бы не было перерисовки?

**Comment by shevdi** [comment]
По хорошему тестируется через публичные функции, которые используют приватные.
