### ISSUE TITLE
Автоматический биндинг

### ISSUE THREAD

**Issue by Burize** [mrNemoZero/life#15]
Это issue "на подумать". 

Сейчас везде, где задаются обработчик на событие 
`this._view.on('startGame',this.startGame.bind(this));` или `this.bindEvent(this.$startButton, 'click', this._clickButtonStart.bind(this));` , нужно прописывать `bind(this)`.

Попробуй автоматизировать биндинг методов. Чтобы при инициализации класса все его методы уже были привязаны к его контексту.  Можно использовать уже готовые решение или свое написать.

**Comment by mrNemoZero** [comment]
Хорошая задачка у меня как раз плохое понимание этого))

**Comment by mrNemoZero** [comment]
хммм, решение использовать стрелочные функции сойдет? При таком функции не привязаны к своему this

**Comment by mrNemoZero** [comment]
Или все же например autobind заюзать??))

**Comment by mrNemoZero** [comment]
хммм, я же правильно понял,что полифиллов нету для стрелочных функций?) А то библиотку auto-bind нельзя юзать из-за них в phantom js))

**Comment by mrNemoZero** [comment]
В итоге ислользовал "auto-bind-es5".

**Comment by Burize** [comment]
Да, так пойдет.  

`хммм, я же правильно понял,что полифиллов нету для стрелочных функций?) А то библиотку auto-bind нельзя юзать из-за них в phantom js))`

Вообще странно, что в auto-bind (точнее в одной из его реализаций) используются стрелочные функции. При биндинге через стрелочные функции методы класса объявляются через них: `func1 = (event) => {};`, а  не через function: `func1(event) {}`, то есть ненужно подключать внешние библиотеки. 
Но в любом случае мы их не используем - при таком биндинге биндится метод для каждого инстанса, но не биндится метод прототипа. Это как минимум плохо при тестировании.

Закрывай issue.
