### ISSUE TITLE
Приватные методы и тесты

### ISSUE THREAD

**Issue by shevdi** [mrNemoZero/life#16]
Приватные методы должны быть скрыты, поэтому они могут быть протестены только опосредованно через публичные методы.
В контроллере nextGeneration будет приватным. Можно протестировать будет ли вызываться changeAllCellsState и drawField

**Comment by mrNemoZero** [comment]
У меня че то не получается функции в интервале проверить :( Кажется уже миллион способов поробывал

**Comment by mrNemoZero** [comment]
В итоге мне так и не получилось проверить nextGeneration за сегодня, продолжу искать завтра решение
Добавил только проверку _isInputCorrect через изменения высоты

**Comment by shevdi** [comment]
Пока оставь пока так. Затестировать setInterval довольно нетривиальная задача. Если совсем туго, то ладно.

**Comment by mrNemoZero** [comment]
А у тебя на своем проекте сработало? Или на моем прям?) Я просто пробовал так тоже и не получилось) Но я щас изменил немного функцию запуска игры, попробую может получится

**Comment by shevdi** [comment]
При клике на кнопку старт проверил, что через секунду был вызвана функция changeAllCellsState, а через полсекунды нет.

**Comment by mrNemoZero** [comment]
круто)Я щас просто далеко от компа через FastHub сижу на телефоне, завтра с утра попробую)

**Comment by mrNemoZero** [comment]
Вот мой тест и у меня он не проходит :) Когда дебажил, он заходил и вызывал функцию changeAllCellsState, но шпион не видит этого хз почему)
**it("должна быть запущена функция _model.changeAllCellsState",()=>{            
            const spy = sinon.spy(Model.prototype,'changeAllCellsState');
            const con = new Controller();
            const clock = sinon.useFakeTimers();
            con._view.$startButton.trigger('click');            
            expect(spy.called).to.be.false;
            clock.tick(1000);
            expect(spy.called).to.be.true;
            spy.restore();
            clock.restore();
          })**

**Comment by shevdi** [comment]
У меня и так проходит тест. Разве что на con._view.$startButton.trigger('click'); ломается.
Можешь попробовать проверку напрямую через sinon.assert.called(spy);

**Comment by mrNemoZero** [comment]
НЕ проходит) А вот Серега мне говорил,что нужен будет линукс т.к. тесты криво будут работать,это не один из этих случаев?)

**Comment by shevdi** [comment]
А я щас с домашнего компа смотрю на windows )

**Comment by shevdi** [comment]
А время пробовал ставить чуть побольше?

**Comment by mrNemoZero** [comment]
аа)) чет я вообще не понимаю пока что с этим делать)))Тем более если ты мой проект запускаешь.
ДА пробовал 100сек поставил все равно)

**Comment by mrNemoZero** [comment]
ХА!)) РЕшил покка в тупике поставить на ноут Линукс, и на нем запустил. Тест прошел  :/

**Comment by shevdi** [comment]
Круть! :+1:
