### ISSUE TITLE
Jquery

### ISSUE THREAD

**Issue by Burize** [mrNemoZero/life#2]
`document.getElementsByClassName и др` - для работы с DOM использовать  jquery, потому что там все полифилы на разные типы браузеров. Не нужно думать, что точно поддерживается везде, а что нет.

**Comment by mrNemoZero** [comment]
Понял,думал тут надо было на чистом TS без Jquery писать, все перепишу

**Comment by Burize** [comment]
Только зачем после того как ты находишь элемент через JQuery, получаешь от туда JS элемент? 
`this.$gameField = $(".js-game-field")[0] as HTMLTableElement;` 
вся суть в том чтобы потом дальше работать с Jquery объектом и использовать его методы заместо стандартных JS. 
И еще, идея  префикса `$` в том, чтобы сразу понять что это объект JQuery и использовать к нему методы этого фреймворка, а не разбираться  является ли это обычным DOM объектом или все-таки JQuery. Сейчас получается у тебя по префиксу это JQuery , но по факту это обычный DOM элемент.

**Comment by mrNemoZero** [comment]
Аааа, все понял для чего это, все переделаю
