### ISSUE TITLE
Код стайл

### ISSUE THREAD

**Issue by Zarwlar** [mrNemoZero/life#20]
Сейчас весь ts код выглядит достаточно зажатым, нужно сделать разрядку (отступы между методами, не пытаться записать всё в одну строку и т.д.)

**Comment by Zarwlar** [comment]
Ещё желательно поставить в своём редакторе отображение whitespace и удалить лишние отступы

**Comment by Zarwlar** [comment]
Ещё внимательно разберись с пробелами. Сейчас у тебя, например, в `const position  = cellPosition.split(",");` Перед равно 2 пробела, но в `if(this._isInputCorrect(width)){` нет ни одного. Эту запись тяжело читать

**Comment by mrNemoZero** [comment]
ну я линтером по всему проекту пройдусь, ну и сам внмательно просмотрю)
