### ISSUE TITLE
Автобиндинг

### ISSUE THREAD

**Issue by Zarwlar** [mrNemoZero/life#21]
По-хорошему его нужно доставать через import, а не через require

**Comment by mrNemoZero** [comment]
это готовое решение там экспорт идет через  **"module.exports"** . Тогд же только реквайрит, при мпорте он пишет не найден модуль. Или я че то туплю?)

**Comment by Zarwlar** [comment]
Вообще, по идее, если ты перешёл на es6, то нужно и использовать соответствующий биндинг, а постольку поскольку ты писал на typescript, то тебе нужна либа-биндинг, для которого есть типы в typesearch

**Comment by mrNemoZero** [comment]
а когда юзаешь es6 биндинг то ругается phantom js(
