### ISSUE TITLE
Развязать модули по максимуму.

### ISSUE THREAD

**Issue by Znack** [mrNemoZero/life#23]
Сейчас у тебя контроллер жестко завязан на модели и вьюхе, от них никуда не уйти теперь. Надо придумать и реализовать архитектуру, которая бы по максимуму развязала бы зависимости все.

**Comment by mrNemoZero** [comment]
Я так понимаю это свзянно с ишью про выделения публичных методов в интерфейсы.?)

Решение создать функцию для назначения вьюхи и модели со входящим элементов стипом интерфейса решить же получается проблему привязанности?Например:
`setView(view: IView){
this.view = view
}`

**Comment by Znack** [comment]
Тогда у тебя возникнет проблема, как быть, если сначала не будет вьюха установлена, а игра запустится? :)

**Comment by mrNemoZero** [comment]
Не ну установка вьюхи будет в конструкторе запускаться или я не правильно что то понял?)

**Comment by Znack** [comment]
а как она будет запускаться, надо тогда полный пример :)

**Comment by mrNemoZero** [comment]
Типа вот так будет. Яначинаю подозревать, что я не правильно понял задачу
> constructor() {
    this.setView(new View());
    this.setModel(new Model());
}

**Comment by mrNemoZero** [comment]
Или надо убрать вообще с конструктора инициализацию Вьюхи и Модели? Организовать так что они будут создаваться когда необходимы? Например при старте игры проверять есть ли ВЬюха и Модель ,если нет, то создать, в ином случае рабоать с ранее созданной, которую поменяли во время паузы например

**Comment by Znack** [comment]
Вот-вот, а то у тебя сейчас, получается, развязывания так и нет :)

**Comment by mrNemoZero** [comment]
Сейчас такая загвоздка возникла, вьюха подписывает события в контроллере.
Как лучше поступить.

- Создать какой нибудь глобальный EventEmiiter и с помощью него подписывать события и во вьюхе и контроллере и эмитить им же?

- Или оставить так же просто подписывать события после создания Вьюхи в контроллере, но пока я не представляю это возможным без создания Вьюхи при инициализации Контроллера, а это опять прямая зависимость(

**Comment by Znack** [comment]
Давай опять развернутый вопрос, ты очень много важных деталей упускаешь :)

**Comment by mrNemoZero** [comment]
Ну вот сейчас как устроено:
Вьюха подписывает на кнопки и инпуты функции которые эмитят события.
Что бы Контроллер мог видеть эти события, которые эмитит Вьюха, ему надо подписываться этой же Вьюхой на события у себя. ЗАдача стоит,что бы контроллер не был зависим от Вьюхи
И пока не понимаю как это сделать. Вот две идеи придумал.
1. Сделать глобальный объект который подписывает и эмитит и у вьюхи и у контроллера, пока не придумал как
2. Подписывать события в контроллере именно после установки в Контроллере Вьюхи. Получается тогда сильной зависимотси нет т.к. мы используем Вьюху только тогда, когда она нам нужна.
Но тогда как сделать, что бы Контроллер делал установку вьюхи если он сам не умеет подписывать на события.
Например: я сделаю,что при кнопке старт идет установка Вьюхи и Модели  у Контроллера,а потом Вьюхой мы подписываем функции Контроллера на события которые она эмитит, но как мне запустит функцию этой инициализации если контроллер не узнает о клике на кнопку старт...

**Comment by Znack** [comment]
`Что бы Контроллер мог видеть эти события, которые эмитит Вьюха, ему надо подписываться этой же Вьюхой на события у себя. ЗАдача стоит,что бы контроллер не был зависим от Вьюхи`— вот это не понял, что значит контроллеру вьюхой подписываться на саму себя?

**Comment by mrNemoZero** [comment]
https://stackoverflow.com/questions/17621285/node-eventemitter-to-eventemitter-emits-multiple-emitters
Я как понял,что EventEmiiter должен быть один, который эмитит события и подписывает на них.
Что бы подписать в Контроллере функции на события которые эмитит Вьюха, надо использовать эту же Вьюху так же для подписи на события в Контроллере. У меня она наследуют от класса EventEmiter и может делать подписи и эмиты этого класса

**Comment by mrNemoZero** [comment]
Может на примере кода понятней будет,что я имею ввиду. 

**Вот кусок во Вьюхе(оставил для кнопки старт). Она ДОМ эелементам привязывает функции, которые эмитят события**
> constructor() {
    super();
    this.initializeDOM();
    autoBind(this);
    this.initializeEvent();
}
private initializeEvent() {
    this.bindEvent(this.$startButton, 'click', this.clickButtonStart);    
  }
> public bindEvent(element: JQuery<HTMLElement>, eventType: string, listener: any) {
    element.on(eventType, listener);
  }
>  private clickButtonStart() {
    this.emit('startGame');
}    

**Это кусок в Контроллере, он вьюхой подписывается на события которая она эмитит, если например я создам отдельно в Контроллере переменную которая подписывает на события или так же наследую от EventEmitter'а, то он не увидит то что эмитит вьюха**
> constructor()
 {
    this.config = require('../config.json');
    this.generationId = 0;
    this.isGameStart = false;
    autoBind(this);
    this.initializeListener();
  }
> public startGame() {
    if (!this.getGameState()) {
      this.setGameState(true);
      this.startGeneration();
    }
  }
  private initializeListener() {
    this.view.on('startGame', this.startGame);   
  }
}

**Comment by mrNemoZero** [comment]
Вот я честно в ступоре, я не доконца понимаю, как лучше сделать. Вот сейчас например, у меня не заданны конструкторе Model, View, но они просто в отдельнйо функции устанавливаются, а эта функция вызывается в конструкторе

**Comment by mrNemoZero** [comment]
А вот как такой вариант, полчается объекты классов Model и View устанавливает Application, а контроллеру передаются только интерфейсы и все.

**Comment by Znack** [comment]
Да, на самом деле неплохо, только теперь тебе надо обрабатывать вызовы initialize перед setModel, что будешь делать в таком случае? :)

**Comment by mrNemoZero** [comment]
Всмысле проверку сделать установлена ли модель и вьюха у контрллера и если нет,то установить по умолчанию?
Я боюсь, что я чего то не улавливаю))

**Comment by mrNemoZero** [comment]
Вот щас хоть когда вызывай работает.

**Comment by Znack** [comment]
Вот, у тебя сейчас отличный пример типичной дилеммы разработчика: сделать систему удобной или сделать систему очевидной. Сейчас если ты не передашь в контроллер вью и запустишь игру, вроде бы ничего не сломается, но и работать не будет. И тот, кто будет твой код поддерживать очень долго не будет понимать, почему так происходит. Так что я бы советовал лучше эксепшен бросать с явным текстом что и где надо исправить, чтобы все работало как надо :) И в будущем всегда следовать правилу, что очевидное лучше вот такого "удобного"

**Comment by mrNemoZero** [comment]
Надеюст я щас правильно) А то я текст 
"**_только теперь тебе надо обрабатывать вызовы initialize перед setModel, что будешь делать в таком случае? :)_**"
ПОдумал, что надо было сделать так , что бы функция  initialize работала всегда без ошибок, а в итоге от нее избавился))

**Comment by Znack** [comment]
Ага, только почитай дополнительно про проверки на потенциально несуществующие объекты и про бросание ошибок :)

**Comment by mrNemoZero** [comment]
Прям не существующие или не инициализированные? Мне надо еще проверку на существования сделать? У меня просто как бы он гарантирует,что у Контроллера есть view, model. А не инициализированные они же всегда 'undefined' и проверка идет? Или я опять че то туплю?)

**Comment by Znack** [comment]
Я имел ввиду, что у тебя проверка не очень корректная, там может быть не undefined, но все равно и не вьюха :)

**Comment by mrNemoZero** [comment]
Забыл в пуш добавть этот ишью. Ошибкт теперь бросает объект Error. Из плюсов увидел только что он показывает место ошибки и как бы сообщение теперь как стандартная ошибка в консоли кидается,а не просто текст))

**Comment by Znack** [comment]
Желательно сделать это через кастомный класс эксепшена :)

**Comment by mrNemoZero** [comment]
А класс оперделить в другом файле лучше же?

**Comment by Znack** [comment]
Ну тут нет единого места, где "оперделять" :)
Сделай там, где сам считаешь нужным, но будь готов доказывать свою позицию, есличто
