### ISSUE TITLE
Именование булиновых переменных

### ISSUE THREAD

**Issue by Znack** [mrNemoZero/life#24]
https://github.com/airbnb/javascript#accessors--boolean-prefix

**Comment by mrNemoZero** [comment]
Есть такая строчка кода, вот по названию мне кажется так оставить лучше, понятно для чего нужна функция. Или убрать эту функцию и сделать которая проверяет например в старте игра или нет, тогда логично назвать **isGameStart** например????)
> public getGameState(): boolean {
    return this.isGameStart;
  }

**Comment by Znack** [comment]
ну геттер можно, да
