### ISSUE TITLE
Странный createNewField у модели

### ISSUE THREAD

**Issue by Znack** [mrNemoZero/life#27]
Там уж либо падай целиком и пусть приложение не работает по явно понятной причине, либо обрабатывай эксепшен

**Comment by mrNemoZero** [comment]
try catch лишний? Я его воткнул,когда у меня что то не получалось и я не мог понять почему и пробовал всякое, уже не помню точно(

**Comment by Znack** [comment]
ну такой код тем более надо либо удалять, либо разбираться детально :) Не надо тыкать костыли, потом оставлять их навсегда в коде, и тем более потом забывать про них, видишь, как неприятно в итоге получается, и мы оба время просто так потратили :)

**Comment by mrNemoZero** [comment]
ДА я забыл вообщее убрать( Я вспомнил там поле не рисовалось в ширину, а причиной было,что из инпутов число как текст передавалось, я на радостях когда решил проблему, про эту штуку вообще забыл(
