### ISSUE TITLE
У классов явно выделить публичные интерфейсы

### ISSUE THREAD

**Issue by Znack** [mrNemoZero/life#28]
Надо отделять контракты, которые гарантирует твой модуль, и конкретную реалзиацию модуля. Представь, опять же, что у тебя могут быть три типа вьюхи — DOM (как сейчас), React-Native, и консольная из Node.js. У них будут явно много общих методов в интерфейсе, а будут некоторые отличительные черты в каждом из них. Так что лучше явно выделить один абстрактный интерфейс, и отдельно интерфейс конкретной реализации. В контроллере, например, на входе можно ждать именно контракт, а не саму реализацию, что для модели, что для вьюхи.

**Comment by mrNemoZero** [comment]
а интерфейс в отдельном файле сделать?А в реализации его импортить?

**Comment by Znack** [comment]
Лучше так, да

**Comment by mrNemoZero** [comment]
У меня архитетура вьюшки подразумевает,что она умеет подписывать на события. Моя ДОМ вьюха наследует от EventEmitter'а фунцкиии такие как "on". Интерфейс для вьхи же будет не логично сделать с функцие on, лучше придумать удачнее название?
Мне не нравится что в моей реаизации вьюхи я по сути напишу обертку для запуска одной функции, но при других релизациях может все по другому будет сделано

**Comment by Znack** [comment]
Можешь более развернуто вопрос задать, я не совсем понял проблемы

**Comment by mrNemoZero** [comment]
Ну я в интерфейсе вьюхи определил функцию "on", которая в моей реализации идет от класса EventEmiiter для подписки событий в Контроллере например. Тут вопрос так и оставить или лучше лучше название придумать?

**Comment by Znack** [comment]
Ну это можешь оставить, это норм
