### ISSUE TITLE
Обработчики событий в отдельные методы класса

### ISSUE THREAD

**Issue by Burize** [mrNemoZero/life#3]
Каждый обработчик (Старта, Паузы и тд) реализовать как отдельный метод класса. Так будет гораздо легче расширять проект в дальнейшем (если бы это был реальный проект), ну и их можно будет переиспользовать; и архитектура будет понятнее.

**Comment by Burize** [comment]
При текущей реализации контроллер знает о внутренностях view. 
`const height: number = +((this._view.$heightField as HTMLInputElement).value); `
Получаеться реализация его методов завязана на архитектуре view. Если в процессе разработки название у $heightField смениться, то это придется учитывать и в контроллере. 
Методы контроллера должны быть подписаны на события view и принимать в качестве аргументов все не обходимые параметры. При таком подходе его можно будет использовать с другим view, у которого высота рассчитывается по другому методу и храниться в другой переменной.

**Comment by mrNemoZero** [comment]
А походу придется,как и было переделывать) Думал сократить код во  view ))

**Comment by mrNemoZero** [comment]
Тесты пока не переделал. Вот подписка в конструкторе контроллера норм сделана?

**Comment by Burize** [comment]
Да, сейчас нормально: контроллер не как не зависит от реализации view, ему нужно знать только какие событие view предоставляет.
