### ISSUE TITLE
Нарушено правило именования файлов

### ISSUE THREAD

**Issue by Znack** [mrNemoZero/life#30]
какие правила у airBnb в стайлгайде относительно имен файлов? :)

**Comment by mrNemoZero** [comment]
23.6 A base filename should exactly match the name of its default export.
**_// good
import CheckBox from './CheckBox'; // PascalCase export/import/filename_**
23.8 Use PascalCase when you export a constructor / class / singleton / function library / bare object.

Экспортирую класс использу. ПскальКейс имя файла должно быть как и имя экспорта по дефолту

**Comment by mrNemoZero** [comment]
Все увидел в интерфейсах неправильно сделал, думал почему что исправленно(
