### ISSUE TITLE
Не нужен лишний массив при апдейте поля в модели

### ISSUE THREAD

**Issue by Znack** [mrNemoZero/life#35]
в Model#changeAllCellsState `newCellsState` вообще не нужен, можно инверсить значение прямо в forEach

**Comment by mrNemoZero** [comment]
да там трабла с тем, что нельзя инвертировать прям сразу т.к. это повлияет на расчет соседей у следу.щей клетке. Поэтому в другойй массив набираю инфу о тех, кто должен измениться и меняю потом в главном

**Comment by mrNemoZero** [comment]
не тот ишью указал это для 36 на самом деле)

**Comment by Znack** [comment]
А, ну да, понял, мутабельность — зло, конечно же. Это ты еще не раз увидешь :) Поэтому и ООП — зло :)

**Comment by mrNemoZero** [comment]
Программирование на темную сторону ведет)) Мне пока так оставить?

**Comment by Znack** [comment]
Ну можешь подумать о более элегантном методе, если сможешь, если не получится, можно и оставить :)

**Comment by mrNemoZero** [comment]
Я конечно подумаю, просто вижу пока, что надо тогда функции класса переделывать, что бы им на вход давался массив при проверке соседей например. Ну я подумаю еще)
