### ISSUE TITLE
Нужно более элегантное решение для подсчета соседей клетки

### ISSUE THREAD

**Issue by Znack** [mrNemoZero/life#36]
Можешь ли сделать без ручного перебора всех соседей?

Сейчас решение неудобно как минимум, потому что там повторяется постоянно `count += this.getCellState(x, y);`, просто меняются параметры, очень тяжко будет, если у getCellState поменяется контракт.

Ну и в целом топорно сейчас решение смотрится, в лоб частный случай сделан, без общего решения :)

**Comment by mrNemoZero** [comment]
а вот такой вид лучше?) Я в пуше не тот ишью указал(

**Comment by Znack** [comment]
Давай еще варианты, не останавливайся на первом пришедшем в голову. И желательно напиши сравнения, какой чем лучше :)

**Comment by mrNemoZero** [comment]
можно добавить на вход каких соседей искать например, а не как сейчас все вокруг просматриваются. Тогд будет более гибкий функционал. Например у нас логика игры будет расширяться и нужны будет соседи с севера,а север будет считатся вверху. Только вопрос как просмотр сделать более понятным а не тупо массивы с [-1,1,0]. Сейчас идея возникла сделаю и запушу

**Comment by mrNemoZero** [comment]
Сейчас фунци **getCountAliveCellNeighbours** принимает на вход параметр где искать соседей, пока кроме как параметра around не используется, но при расширении фугкционала и может понадобиться. Например я видел на хабре реализацию этой Игры уже с хищниками и травоядными, можно еще самому много че придумать. Добавить функционал убегать от хищников травоядным, тогда надо будет убегать в одном направлении и проверить именно тех соседей которые встречаются на пути

**Comment by mrNemoZero** [comment]
Правда не уверен,что при каждом вызове getRangeX или getRangeY создается константа, ее наверное лучше вынести в инициализаю в конструкторе

**Comment by Znack** [comment]
Да константа пофиг, она подтерется сборщиком

А вот то, что у тебя левый человек мозг сломает, прежде чем твой шифр поймет — проблема :)
Главное всегда в разработке — чтобы коллегам было просто и понятно. Оптимизация, кол-во строк кода и символов в строке — все потом, главное — понятность :)

**Comment by Znack** [comment]
Все равно у тебя мозг ломается на текущем решении :)
У тебя два метода должны быть идеально синхронизированы, и очень легко там допустить ошибку — в одном не туда единицу поставил, а ошибка будет по сути в другом, так как координаты не сошлись. Такие узкие места в логике всегда надо локализовать :)

**Comment by mrNemoZero** [comment]
Я тогда объединю их в один метод. Ну и подумаю как лучше сделать)

**Comment by mrNemoZero** [comment]
Я вот все же не могу понять. от этих цифр все рано никуда не денешься или я туплю что то)
Сейчас объеденил в один метод.

**Comment by Znack** [comment]
Смотря от каких цифр и смотря куда деться, думай, как упростить максимально решение, а точнее сделать его более понятным, насколько это возможно :)

**Comment by mrNemoZero** [comment]
я не понял, как здесь меньшен делать поэтому просто напишу =)

**Comment by mrNemoZero** [comment]
@Znack

**Comment by Znack** [comment]
Меншен работает :) А код у тебя до сих пор очень многословный и переусложненный :)

**Comment by mrNemoZero** [comment]
я думал наоборот упростил^^... указав вроде как бы все явно.

**Comment by mrNemoZero** [comment]
@Znack  перечитал с чего ишью началось и когда почитал про функцию reduce по чек листу пришел к такой идее. Ручного перебора нет, код вроде не переусложнен )) Только вот добавилась еще одна проверка на то, что бы не ячейку саму себя не считали соседом

**Comment by Znack** [comment]
Да, это решение на порядки лучше, не зря ты страдал все это время :)

**Comment by mrNemoZero** [comment]
Да неправильно еще изначально понял, начал какую то ересь мудрить)
