### ISSUE TITLE
Код не изолирован

### ISSUE THREAD

**Issue by Znack** [mrNemoZero/life#38]
Две параллельных игры ты не запустишь на одной странице, это необязательно, конечно, но это признак непродуманной архитектуры :)
Части твоей системы должны быть изолированы и самодостаточны по максимуму

**Comment by mrNemoZero** [comment]
Вот этот кусок у мея сложный
`(neighbours < 2 || neighbours > 3)`
но следом идет простой, и вот его вроде как и не надо по стандартам в метод пихать. Но будет не очень как то, если первая проверка будет в методе,а вторая нет, как лучше поступить их обоих в методы все равно запихать?
`(neighbours === 3)`

**Comment by mrNemoZero** [comment]
Ого я загнал, это в ишью 37 было адресованно xD **"Сложные условия по стандартам надо выносить в отдельные методы #37"**

**Comment by mrNemoZero** [comment]
Тогда мне рендерить ДОМ во вьюхе тоже получается?) Это уже как в Реакте будет)

**Comment by Znack** [comment]
Я не буду тебе тут решения говорить, я тебе даже проблему конкретную специально не называл :) Я тебе просто сказал об архитектурном пропуске, а какие он порождает конкретные проблемы, и тем более как их решать, надо тебе думать :)

**Comment by mrNemoZero** [comment]
ну вот давай первый вариант, ща изолировал и две игрыможно запустить)

**Comment by Znack** [comment]
На первый взгляд пойдет, но запомни на будущее, что такие вещи сразу надо проектировать :) Сразу думать о том, чтобы можно было два и больше инстансов твоих классов создавать и они бы друг на друга не влияли

**Comment by mrNemoZero** [comment]
Да теперь буду иметь ввиду это всегда) В изначальном условвии задачи не говорилось, про несколько приложений, а сам и не додумался продумать это)
