### ISSUE TITLE
parseInt не по стандартам

### ISSUE THREAD

**Issue by Znack** [mrNemoZero/life#40]

**Comment by mrNemoZero** [comment]
Если про мой вот это "код"
`height: number = parseInt(this.$heightField.val() as string);`
Это же наоборот явный привод к типу,? А в стандартах написано избегать неявного. Без as string TS ругается,что это не ясно,что за тип, что бы использовать методы JQuery приходится так делать.  ДО этого стояло тупо 
`height: number = this.$heightField.val() as number;`
Но при перерисовке он его как String в итоге передавал(

**Comment by Znack** [comment]
Это не про приведение типов, перечитывай стандарты :)

**Comment by mrNemoZero** [comment]
Все теперь понял)
