### ISSUE TITLE
импорт json файла в контроллере вынести в начало файла

### ISSUE THREAD

**Issue by shevdi** [mrNemoZero/life#43]

**Comment by mrNemoZero** [comment]
А вот этот момент хочу уточнить) У меня сейчас в конструкторе импортится и мне кажется так правильно. Если ли импортнуть в начале файла то для всех созданных контроллерах останется один и тот же период времени. А если надо менять время,то надо брать текущие данные в момент создания контроллера? Или для такого случая надо будет метод для изменения периода времени вставлять?

**Comment by shevdi** [comment]
Пожалуй, логичнее будет заимпортить конфиг в application.ts и передать аргументом при создании контроллера.

**Comment by mrNemoZero** [comment]
да логичней, так и сделаю)
