### ISSUE TITLE
Полифилы 

### ISSUE THREAD

**Issue by Burize** [mrNemoZero/life#9]
Такие методы как Array.From и Array.fill поддерживаются не всеми браузерами, поэтому они требуют полифилов. 
Причем тут суть даже не в том, чтобы игра работала в IE. При тестировании часто используются подключаемые браузеры например http://phantomjs.org/ ,( тогда не нужно будет запускать отдельное окна для chrome при тестировании; так обычно и делают) и он не поддерживает эти методы. 
Нужно задать полифилы для них. Полифилы должны быть в отдельной папке, а не там где используется этот метод

**Comment by mrNemoZero** [comment]
Установил полифиллы через npm и подключил их в классе модели

**Comment by mrNemoZero** [comment]
Это мне 
Серега в риззоме ответил, что лучше сделать через npm
